"""Email service — send formatted HTML itinerary via Gmail SMTP."""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ── Category colour palette ───────────────────────────────────────────────────
_CATEGORY_COLORS = {
    "Food": "#f59e0b",
    "History": "#3b82f6",
    "Adventure": "#10b981",
    "Culture": "#8b5cf6",
    "Nature": "#14b8a6",
    "Shopping": "#ec4899",
    "Relaxation": "#0ea5e9",
}


def _build_html(itinerary: dict) -> str:
    destination = itinerary.get("destination", "Your Destination")
    country = itinerary.get("country", "")
    duration = itinerary.get("duration", "")
    summary = itinerary.get("summary", "")
    tips = itinerary.get("tips", [])
    days = itinerary.get("days", [])

    # Tips HTML
    tips_html = "".join(f"<li style='margin:6px 0;color:#374151;'>{t}</li>" for t in tips)

    # Days HTML
    days_html = ""
    for day_obj in days:
        activities_html = ""
        for act in day_obj.get("activities", []):
            cat = act.get("category", "General")
            color = _CATEGORY_COLORS.get(cat, "#6366f1")
            activities_html += f"""
            <div style="border-left:3px solid {color};padding:10px 15px;margin:10px 0;background:#f9fafb;border-radius:0 8px 8px 0;">
              <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;">
                <strong style="color:#111827;font-size:15px;">{act.get('time','')} — {act.get('title','')}</strong>
                <span style="background:{color};color:white;padding:2px 10px;border-radius:20px;font-size:12px;">{cat}</span>
              </div>
              <p style="margin:6px 0;color:#4b5563;font-size:14px;">📍 {act.get('location','')} &nbsp;|&nbsp; ⏱ {act.get('duration','')} &nbsp;|&nbsp; 💰 {act.get('cost','')}</p>
              <p style="margin:6px 0;color:#374151;font-size:14px;">{act.get('description','')}</p>
              <p style="margin:4px 0;color:#6b7280;font-size:13px;font-style:italic;">💡 {act.get('tip','')}</p>
            </div>"""

        days_html += f"""
        <div style="margin:24px 0;background:white;border-radius:12px;box-shadow:0 1px 4px rgba(0,0,0,0.08);overflow:hidden;">
          <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:16px 20px;">
            <h3 style="margin:0;color:white;font-size:18px;">Day {day_obj.get('day','')} — {day_obj.get('theme','')}</h3>
          </div>
          <div style="padding:16px;">
            {activities_html}
          </div>
        </div>"""

    return f"""
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Your TripCraft AI Itinerary</title></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#6366f1 0%,#8b5cf6 50%,#a855f7 100%);padding:40px 24px;text-align:center;">
    <p style="color:#c4b5fd;margin:0 0 8px 0;font-size:14px;letter-spacing:2px;text-transform:uppercase;">TripCraft AI</p>
    <h1 style="color:white;margin:0 0 8px 0;font-size:32px;font-weight:700;">{destination}</h1>
    <p style="color:#e9d5ff;margin:0;font-size:16px;">{country} &nbsp;·&nbsp; {duration}-Day Itinerary</p>
  </div>

  <!-- Body -->
  <div style="max-width:640px;margin:0 auto;padding:24px 16px;">

    <!-- Summary -->
    <div style="background:white;border-radius:12px;padding:20px;margin-bottom:24px;box-shadow:0 1px 4px rgba(0,0,0,0.08);">
      <h2 style="margin:0 0 10px 0;color:#1f2937;font-size:18px;">Trip Overview</h2>
      <p style="margin:0;color:#4b5563;line-height:1.7;">{summary}</p>
    </div>

    <!-- Days -->
    {days_html}

    <!-- Tips -->
    <div style="background:white;border-radius:12px;padding:20px;margin-top:24px;box-shadow:0 1px 4px rgba(0,0,0,0.08);">
      <h2 style="margin:0 0 10px 0;color:#1f2937;font-size:18px;">✈️ Traveller Tips</h2>
      <ul style="margin:0;padding-left:20px;">{tips_html}</ul>
    </div>

    <!-- Footer -->
    <p style="text-align:center;color:#9ca3af;font-size:12px;margin-top:32px;">
      Generated by <strong>TripCraft AI</strong> · Powered by Google Gemini<br>
      Have a wonderful trip! 🌍
    </p>
  </div>
</body>
</html>"""


def send_itinerary_email(recipient: str, itinerary: dict) -> dict:
    smtp_email = os.getenv("SMTP_EMAIL")
    smtp_password = os.getenv("SMTP_PASSWORD")

    if not smtp_email or not smtp_password:
        return {"success": False, "error": "SMTP credentials not configured on the server."}

    destination = itinerary.get("destination", "Your Trip")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"✈️ Your {destination} Itinerary — TripCraft AI"
    msg["From"] = f"TripCraft AI <{smtp_email}>"
    msg["To"] = recipient

    html_body = _build_html(itinerary)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, recipient, msg.as_string())

        return {"success": True, "message": f"Itinerary sent to {recipient}"}
    except smtplib.SMTPAuthenticationError:
        return {"success": False, "error": "Gmail authentication failed. Check SMTP_EMAIL and SMTP_PASSWORD."}
    except Exception as exc:
        return {"success": False, "error": str(exc)}
