import jsPDF from 'jspdf'

const INDIGO = [99, 102, 241]
const VIOLET = [139, 92, 246]
const DARK   = [31, 41, 55]
const GRAY   = [107, 114, 128]
const LIGHT  = [156, 163, 175]

function addPageIfNeeded(doc, y, needed = 20) {
  if (y + needed > 275) {
    doc.addPage()
    return 20
  }
  return y
}

export function exportItineraryPDF(itinerary) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pw = 170 // printable width (210 - 2*20 margins)
  let y = 0

  // ── Cover header bar ──────────────────────────────────────────────
  doc.setFillColor(...INDIGO)
  doc.rect(0, 0, 210, 38, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(itinerary.destination || 'Trip', 20, 18)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `${itinerary.country || ''}   ·   ${itinerary.duration || ''}-Day Itinerary`,
    20,
    27
  )

  doc.setFontSize(8)
  doc.setTextColor(199, 210, 254)
  doc.text('Generated by TripCraft AI', 20, 35)

  y = 48

  // ── Summary ───────────────────────────────────────────────────────
  if (itinerary.summary) {
    doc.setTextColor(...DARK)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(itinerary.summary, pw)
    doc.text(lines, 20, y)
    y += lines.length * 5 + 8
  }

  // ── Tips ──────────────────────────────────────────────────────────
  if (itinerary.tips?.length) {
    y = addPageIfNeeded(doc, y, 20)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INDIGO)
    doc.text('Traveller Tips', 20, y)
    y += 6

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    for (const tip of itinerary.tips) {
      y = addPageIfNeeded(doc, y, 10)
      const tipLines = doc.splitTextToSize(`• ${tip}`, pw - 5)
      doc.text(tipLines, 22, y)
      y += tipLines.length * 4 + 2
    }
    y += 6
  }

  // ── Days ──────────────────────────────────────────────────────────
  for (const day of itinerary.days || []) {
    y = addPageIfNeeded(doc, y, 30)

    // Day header pill
    doc.setFillColor(...VIOLET)
    doc.roundedRect(20, y - 4, pw, 10, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(`Day ${day.day}  —  ${day.theme || ''}`, 24, y + 3)
    y += 12

    // Activities
    for (const act of day.activities || []) {
      y = addPageIfNeeded(doc, y, 24)

      // Time + title
      doc.setTextColor(...INDIGO)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text(act.time || '', 20, y)

      doc.setTextColor(...DARK)
      doc.setFont('helvetica', 'bold')
      const titleLines = doc.splitTextToSize(act.title || '', pw - 18)
      doc.text(titleLines, 36, y)
      y += titleLines.length * 4 + 1

      // Meta: location · duration · cost
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(...GRAY)
      const meta = [act.location, act.duration, act.cost].filter(Boolean).join('   ·   ')
      doc.text(meta, 36, y)
      y += 4

      // Description
      doc.setFontSize(8.5)
      doc.setTextColor(...DARK)
      const descLines = doc.splitTextToSize(act.description || '', pw - 16)
      doc.text(descLines, 36, y)
      y += descLines.length * 4 + 5
    }
    y += 4
  }

  // ── Footer on every page ──────────────────────────────────────────
  const total = doc.internal.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFontSize(7.5)
    doc.setTextColor(...LIGHT)
    doc.text('TripCraft AI  ·  Powered by Google Gemini', 20, 291)
    doc.text(`${i} / ${total}`, 195, 291, { align: 'right' })
  }

  doc.save(`${itinerary.destination || 'itinerary'}-TripCraft.pdf`)
}
